version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aidvokat
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      retries: 10
    volumes:
      - redisdata:/data

  minio:
    image: minio/minio:RELEASE.2023-10-16T17-48-27Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - miniodata:/data

  minio-mc:
    image: minio/mc:RELEASE.2023-10-16T17-57-30Z
    depends_on:
      - minio
    entrypoint: |
      /bin/sh -c "
        mc config host add local http://minio:9000 minioadmin minioadmin &&
        mc mb -p local/aidvokat-exports || true
      "

volumes:
  pgdata:
  redisdata:
  miniodata:
